name: server_vault
description: SSH client app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartssh2: ^2.9.0
  xterm: ^4.0.0
  sqflite: ^2.3.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  uuid: ^4.0.0
  crypto: ^3.0.3
  file_picker: ^6.1.1
  path: ^1.8.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  path: ^1.9.0
  drift_dev: ^2.29.0
  build_runner: ^2.9.0

flutter:
  uses-material-design: true